# Generated by Django 4.2.7 on 2023-12-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('soccer_skills', models.CharField(choices=[('Dribbling', 'Dribbling'), ('Passen', 'Passing'), ('Torschuss', 'Finishing'), ('Ballannahme', 'Trapping'), ('Zusammenspiel', 'Cooperation')], max_length=50, null=True)),
                ('age_adults', models.BooleanField(default=True)),
                ('age_jun_a', models.BooleanField(default=False)),
                ('age_jun_b', models.BooleanField(default=False)),
                ('age_jun_c', models.BooleanField(default=False)),
                ('age_jun_d', models.BooleanField(default=False)),
                ('age_jun_e', models.BooleanField(default=False)),
                ('age_jun_f', models.BooleanField(default=False)),
                ('age_jun_g', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercise.creator')),
            ],
        ),
    ]
