# Generated by Django 4.2.9 on 2024-01-12 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "soccer_skills",
                    models.CharField(
                        choices=[
                            ("Dribbling", "Dribbling"),
                            ("Passen", "Passing"),
                            ("Torschuss", "Finishing"),
                            ("Ballannahme", "Trapping"),
                            ("Zusammenspiel", "Cooperation"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("for_adults", models.BooleanField(default=True)),
                ("for_jun_a", models.BooleanField(default=False)),
                ("for_jun_b", models.BooleanField(default=False)),
                ("for_jun_c", models.BooleanField(default=False)),
                ("for_jun_d", models.BooleanField(default=False)),
                ("for_jun_e", models.BooleanField(default=False)),
                ("for_jun_f", models.BooleanField(default=False)),
                ("for_jun_g", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="exercise/images/"
                    ),
                ),
                ("pdf", models.FileField(blank=True, upload_to="exercise/pdfs/")),
                ("youtube_link", models.URLField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
