# Generated by Django 4.2.7 on 2023-12-21 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoccerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.AddField(
            model_name='exercise',
            name='body',
            field=models.TextField(default='bla'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(default='title bla', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='soccer_skills',
            field=models.ManyToManyField(related_name='exercises', to='exercise.soccerskill'),
        ),
    ]
