# Generated by Django 4.2.9 on 2024-01-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0002_exercise_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0
            ),
        ),
    ]
