# Generated by Django 4.2.7 on 2023-12-22 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0002_soccerskill_remove_exercise_description_and_more"),
    ]

    operations = []
