# Generated by Django 4.2.7 on 2023-12-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0003_auto_20231222_1358"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name="soccerskill",
            old_name="name",
            new_name="label",
        ),
        migrations.AddField(
            model_name="exercise",
            name="age_groups",
            field=models.ManyToManyField(
                related_name="exercises", to="exercise.agegroup"
            ),
        ),
    ]
